server:
  port: 8080

spring:
  #数据库连接配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/employment_manage_system?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
    use-global-data-source-stat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    druid:
      # 监控台
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
      # 过滤器
      web-stat-filter:
        enabled: true

  # 文件上传
  servlet:
    multipart:
      enabled: true #开启文件上传支持
      file-size-threshold: 0  #文件写入磁盘阈值
      location: E:\\upload  #文件上传临时保存位置
      max-file-size: 20MB  #单个文件时上传的最大大小
      max-request-size: 100MB #多个文件时上传的最大大小
      resolve-lazily: false #文件是否延迟解析

mybatis:
  # 设置mapper文件的扫描路径
  mapper-locations: classpath:com/zl/employment/mapper/*.xml
  # 设置POJO别名扫描包
  type-aliases-package: com/zl/employment/pojo

# 分页助手
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql